require 'seed_cleaner'
# include SeedCleaner

noun = [
  %w[freund masculin friend people],
  %w[mann masculin man people],
  %w[fahrer masculin driver people],
  %w[frau feminin woman people],
  %w[kellner masculin waiter people],
  %w[freundin feminin friend(fem.) people],
  %w[feuerwehrfrau feminin firefighter(fem.) people],
  %w[Ärztin feminin doctor(fem.) people],
  %w[Anwältin  feminin lawyer(fem.) people],
  %w[frauen plurial women people],
  %w[mutter feminin mother people],
  %w[Mädchen neutral girl people],
  %w[Mädchen plurial girls people],
  %w[Junge masculin boy people],
  %w[Jungen plurial boys people],
  %w[kerl masculin dude people],
  %w[kind neutral kid people],
  %w[Ehefrau feminin wife people],
  %w[Ehefrauen plurial wives people],
  %w[bruder masculin brother people],
  %w[sohn masculin son people],
  %w[Schwester feminin sister people],
  %w[Schwestern plurial sisters people],
  %w[Tochter feminin daugther people],
  %w[Ehemann masculin husband people],
  %w[Ehepaar neutral couple people],
  %w[Person feminin person people],
  %w[Vater masculin father people],
  %w[Dame feminin lady people],
  %w[Onkel masculin onkel people],
  %w[Gruppe feminin group people],
  %w[Schüler masculin student people],
  %w[Erzähler masculin narrator people],
  %w[König masculin king people],
  %w[Offizier masculin officer people],
  %w[Tante feminin aunt people],
  %w[Polizistin feminin policewoman people],
  %w[Lehrerin feminin teacher(fem.) people],
  #
  %w[stadt feminin city place],
  %w[länder plurial countries place],
  %w[weg masculin way place],
  %w[schule feminin school building],
  %w[amt neutral office building],
  %w[gebäude neutral building building],
  %w[haus neutral house building],
  %w[ort masculin place place],
  %w[Straße feminin street place],
  %w[Straßen plurial streets place],
  %w[Ecke feminin corner place],
  %w[Hölle feminin hell place],
  %w[Wohnung feminin apartement place],
  %w[Wohnungen plurial apartements place],
  %w[Küche feminin kitchen place],
  %w[Bar feminin bar place],
  %w[Schlafzimmer neutral bedroom place],
  %w[Bahnhof masculin trainstation place],
  %w[Geschäft neutral store place],
  %w[Berg masculin montain place],
  %w[Kirche feminin church place],
  %w[Krankenhaus neutral hospital place],
  %w[Hof masculin yard place],
  %w[Loch neutral hole place],
  %w[Dorf neutral village place],
  #
  %w[auto neutral car vehicule],
  %w[fahrrad neutral bike vehicule],
  %w[Schiff neutral ship vehicule],
  %w[Lkw masculin truck vehicule],
  %w[Boot masculin boat vehicule],
  %w[Zug masculin train vehicule],
  %w[Bus masculin bus vehicule],
  #
  %w[pizza feminin pizza food],
  %w[kurbis masculin pumpkin food],
  %w[bratwurst feminin sausage food],
  %w[bohne plurial beans food],
  %w[nudeln plurial pasta food],
  %w[brot neutral bread food],
  %w[Essen neutral meal food],
  %w[Abendessen neutral dinner food],
  %w[wasser neutral water drink],
  %w[tee masculin tea drink],
  %w[kaffee masculin coffee drink],
  %w[saft masculin juice drink],
  %w[bier neutral bier drink],
  %w[Flasche feminin bottle drink],
  %w[Getränk neutral drink drink],
  %w[Tasse feminin cup drink],
  #
  %w[Tür feminin door object],
  %w[teile plurial parts object],
  %w[tisch masculin table object],
  %w[bett neutral bed object],
  %w[buch neutral book object],
  %w[schutzhelm masculin helmet object],
  %w[handy neutral cellular object],
  %w[baum masculin tree object],
  %w[papier neutral paper object],
  %w[beutel masculin bag object],
  %w[kiste feminin box object],
  %w[Stück neutral piece object],
  %w[ding neutral thing object],
  %w[Tabellen plurial tables object],
  %w[Telefon neutral phone object],
  %w[Telefone plurial phones object],
  %w[Stuhl masculin chair object],
  %w[Taschen plurial bags object],
  %w[Waffe feminin weapon object],
  %w[stein masculin stone object],
  %w[steine plurial stones object],
  %w[Geld neutral money object],
  %w[Feuer neutral fire object],
  %w[Bild neutral picture object],
  %w[Brief masculin letter object],
  %w[Fels masculin rock object],
  %w[Kleid neutral dress object],
  %w[Schild neutral sign object],
  %w[Holz neutral wood object],
  %w[Hemd neutral shirt object],
  %w[Rechnung feminin bill object],
  %w[Schuh masculin shoe object],
  %w[Bildschirm masculin screen object],
  %w[Anzug masculin suit object],
  %w[Kamera feminin camera object],
  %w[Karte feminin card object],
  %w[Schnee masculin snow object],
  %w[Spiegel masculin mirror object],
  %w[Mantel masculin coat object],
  %w[Hut masculin hat object],
  %w[Zigarette feminin cigarette object],
  %w[Schlüssel masculin key object],
  %w[Blume feminin flower object],
  %w[Teller masculin plate object],
  %w[Jacke feminin jacket object],
  %w[Messer neutral knife object],
  #
  %w[hund masculin dog animal],
  %w[hunde plurial dogs animal],
  %w[katze feminin cat animal],
  %w[schildkröte feminin turtle animal],
  %w[pferd neutral horse animal],
  %w[Vogel masculin bird animal],
  %w[Tier neutral animal animal],
  %w[Fisch masculin fish animal],
  #
  %w[klang masculin sound sound],
  %w[musik feminin music sound],
  %w[alarm masculin alarm sound],
  %w[stimme feminin voice sound],
  %w[Geräusch neutral noise sound],
  %w[Nachricht feminin news read],
  %w[stoizismus masculin stoicism idea],
  %w[philosophie feminin philosophy idea],
  %w[maskottchen neutral mascot idea],
  %w[steuern plurial taxes idea],
  ]
  # %w[glas neutral glass drink/object]
  # %w[buch neutral book readable]
  # %w[arbeit feminin work activity]
  # %w[geschichte feminin story language]
  # %w[gott masculin god concept/divinity]
  # %w[jahr neutral year time],
  # %w[hand feminin hand body],
  # %w[hande plurial hands body],
  # %w[Auge neutral eye body],
  # %w[Kopf masculin head body],
  # %w[Arm masculin arm body],
  # %w[Fuß masculin foot body],
  # %w[Körper masculin body body],
  # %w[Mund masculin mouth body],
  # %w[Herz neutral heart body],
  # %w[Bein neutral leg body],
  # %w[Blut neutral blood body],
  # %w[Lippe feminin lip body],
  # %w[Haut feminin skin body],
  # %w[Ohr neutral ear body],
  # %w[Hals masculin neck body],
  # %w[Brust feminin chest body],
  # %w[Nase feminin nose body],
  # %w[Zahn masculin tooth body],

nouns_check_array = []

noun.each do |array|
  nouns_check_array << Noun.find_or_create_by!(
    value: array[0],
    gender: array[1],
    english: array[2],
    kind: array[3]
      )
end



puts 'The following nouns were deleted because they were neither found or created:'
p SeedCleaner.clean(nouns_check_array, Noun)

puts 'Nouns are seeded!'


